# Site settings
title: "Microsoft Fabric User Group Austria"
email: hannes.alkin@datenexperten.at
description: "Microsoft Fabric & Power BI User Group Austria"
keywords: "MicrosoftFabric, Fabric, PowerBI, DataEngineering, Austria, UserGroup"
baseurl: ""
url: "https://fabric-user-group-austria.at"

# Build settings
markdown: kramdown
permalink: pretty
sass:
  sass_dir: _sass/
  style: compressed
plugins:
- jekyll-sitemap

collections:
  community:
    permalink: :path/
  plauscherl:
    output: true
    permalink: /:name/
